#!/bin/bash

# Set an admin login and password for your database
export adminlogin=dbadmin
export password="Pa55w.rd1234"
# The logical server name has to be unique in the system
export servername=gabc2018fachdbsvr-$RANDOM
# The ip address range that you want to allow to access your DB
export startip=10.0.0.1
export endip=10.0.0.255

# Create a resource group
az group create \
	--name gabc2018fach \
	--location eastus

# Create a logical server in the resource group
az sql server create \
	--name $servername \
	--resource-group gabc2018fach \
	--location eastus  \
	--admin-user $adminlogin \
	--admin-password $password

# Configure a firewall rule for the server
az sql server firewall-rule create \
	--resource-group gabc2018fach \
	--server $servername \
	-n AllowYourIp \
	--start-ip-address $startip \
	--end-ip-address $endip

# Create a database in the server with zone redundancy as true
az sql db create \
	--resource-group gabc2018fach \
	--server $servername \
	--name gabc2018SampleDatabase \
	--sample-name AdventureWorksLT \
	--service-objective S0
	--zone-redundant

# Update database and set zone redundancy as false
az sql db update 
	--resource-group gabc2018fach \
	--server $servername \
	--name gabc2018SampleDatabase \
	--zone-redundant false
